image: node:10.8.0-stretch

before_script:
  - npm install

cache:
  paths:
    - node_modules/

lint:
  script:
    - npm run lint

test:
  script:
    - npm run test

audit:
  script:
    - npm audit
