language: node_js
node_js:
  - "node"

before_script:
  - npm install

cache:
  directories:
    - "node_modules"

script:
- npm run lint
- npm run test
- nyc npm test && nyc report --reporter=text-lcov | coveralls
- npm audit
